
--This file was autogenerated from c_test.c
package Sv_m.Constants is
use C;

  C_ERROR      : constant C.Int :=  -1 ;

  IPC_CREAT    : constant C.Int :=  512 ; 
  IPC_EXCL     : constant C.Int :=  1024 ; 
  IPC_INFO     : constant C.Int :=  3 ; 
  IPC_NOWAIT   : constant C.Int :=  2048 ; 
  IPC_PRIVATE  : constant C.Int :=  0 ; 
  IPC_RMID     : constant C.Int :=  0 ; 
  IPC_SET      : constant C.Int :=  1 ; 
  IPC_STAT     : constant C.Int :=  2 ; 

  E2BIG        : constant C.Int :=  7 ; --  Argument list too long
  EACCES       : constant C.Int :=  13 ; --  Permission denied
  EAGAIN       : constant C.Int :=  11 ; --  Resource temporarily unavailable
  EBADF        : constant C.Int :=  9 ; --  Bad file descriptor
  EBADMSG      : constant C.Int :=  74 ; --  Bad message
  EBUSY        : constant C.Int :=  16 ; --  Device or resource busy
  ECANCELED    : constant C.Int :=  125 ; --  Unknown error 125
  ECHILD       : constant C.Int :=  10 ; --  No child processes
  EDEADLK      : constant C.Int :=  35 ; --  Resource deadlock avoided
  EDOM         : constant C.Int :=  33 ; --  Numerical argument out of domain
  EEXIST       : constant C.Int :=  17 ; --  File exists
  EFAULT       : constant C.Int :=  14 ; --  Bad address
  EFBIG        : constant C.Int :=  27 ; --  File too large
  EINPROGRESS  : constant C.Int :=  115 ; --  Operation now in progress
  EINTR        : constant C.Int :=  4 ; --  Interrupted system call
  EINVAL       : constant C.Int :=  22 ; --  Invalid argument
  EIO          : constant C.Int :=  5 ; --  Input/output error
  EIDRM        : constant C.Int :=  43 ; --  Identifier removed
  EISDIR       : constant C.Int :=  21 ; --  Is a directory
  EMFILE       : constant C.Int :=  24 ; --  Too many open files
  EMLINK       : constant C.Int :=  31 ; --  Too many links
  EMSGSIZE     : constant C.Int :=  90 ; --  Message too long
  ENAMETOOLONG : constant C.Int :=  36 ; --  File name too long
  ENFILE       : constant C.Int :=  23 ; --  Too many open files in system
  ENODEV       : constant C.Int :=  19 ; --  No such device
  ENOENT       : constant C.Int :=  2 ; --  No such file or directory
  ENOEXEC      : constant C.Int :=  8 ; --  Exec format error
  ENOLCK       : constant C.Int :=  37 ; --  No locks available
  ENOMEM       : constant C.Int :=  12 ; --  Cannot allocate memory
  ENOMSG       : constant C.Int :=  42 ; --  No message of desired type
  ENOSPC       : constant C.Int :=  28 ; --  No space left on device
  ENOSYS       : constant C.Int :=  38 ; --  Function not implemented
  ENOTDIR      : constant C.Int :=  20 ; --  Not a directory
  ENOTEMPTY    : constant C.Int :=  39 ; --  Directory not empty
  ENOTSUP      : constant C.Int :=  95 ; --  Operation not supported
  ENOTTY       : constant C.Int :=  25 ; --  Inappropriate ioctl for device
  ENXIO        : constant C.Int :=  6 ; --  No such device or address
  EPERM        : constant C.Int :=  1 ; --  Operation not permitted
  EPIPE        : constant C.Int :=  32 ; --  Broken pipe
  ERANGE       : constant C.Int :=  34 ; --  Numerical result out of range
  EROFS        : constant C.Int :=  30 ; --  Read-only file system
  ESPIPE       : constant C.Int :=  29 ; --  Illegal seek
  ESRCH        : constant C.Int :=  3 ; --  No such process
  ETIMEDOUT    : constant C.Int :=  110 ; --  Connection timed out
  EXDEV        : constant C.Int :=  18 ; --  Invalid cross-device link
end Sv_m.Constants;
